name: Build

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  push:
    branches: 
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
    build:
        name: Build

        strategy:
          matrix:
            # See available versions & paths: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
            xcode-version: ["14.3.1", "15.0"]

        runs-on: [macos-13]
    
        defaults:
          run:
            shell: zsh {0}

        concurrency: 
          group: integration-tests-${{ github.ref }}-${{ matrix.xcode-version }}
          cancel-in-progress: true
    
        env:
          XCODE_VERSION_PATH: /Applications/Xcode_${{ matrix.xcode-version }}.app

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Xcode version
            run: sudo xcode-select -s ${{ env.XCODE_VERSION_PATH }}
    
          - name: Build Package
            run: swift build
